sudo: required
services:
  - docker

before_install:
  - docker build -t issabayevmk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true issabayevmk/docker-react npm run test -- --coverage